current_user_count: 0
init: true
last_login: 1543737600000
password: your_password_here
portal_url: https://claremont.maps.arcgis.com
reset_login: 1543737600000
username: your_username_here
dashboard_item: your_dashboard_item_id_here
usage_view_item: your_usageview_item_id_here
usage_item: your_usage_item_id_here
users_by_campus: your_users_here
